---
# Reference: This code is based on the instructions from the following article:
# https://defgw.wordpress.com/2017/10/24/watchdog-reboot-raspberry-pi-if-network-is-down/

# TODO: reboot the server after instalation
- name: Install watchdog package
  package:
    name: watchdog
    state: present

- name: Update /etc/watchdog.conf
  blockinfile:
    path: /etc/watchdog.conf
    backup: true
    block: |
      interface = wlan0
      ping-count = 10
      ping = 8.8.8.8
      interval = 30
  notify:
    - stop service
    - start service

- name: Enable and start
  systemd_service:
    name: watchdog
    state: started
    enabled: true
