---
- name: Start a zabbix-agent container
  docker_container:
    name: zabbix-agent
    image: zabbix/zabbix-agent2:alpine-6.4-latest
    state: started
    restart_policy: unless-stopped
    privileged: true
    hostname: "{{ ansible_hostname }}"
    network_mode: host
    ports:
      - 10050:10050
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    groups:
      - "999"  # docker (Ubuntu 22.04)
      - "994"  # docker (Debian 12)
    labels:
      reproxy.enabled: "false"
    env:
      ZBX_SERVER_HOST: "zabbix,127.0.0.1"
      ZBX_HOSTNAME: "{{ ansible_hostname }}"
