---
timezone: America/Toronto
common_packages:
  - ethtool
  - git
  - htop
  - iperf3
  - iputils-ping
  - lshw
  - lsof
  - net-tools
  - psmisc
  - rsync
  - tcpdump
  - tree
  - vim

useless_packages:
  - iperf3
