---
- name: Stop systemd-resolved service
  systemd_service:
    name: systemd-resolved
    state: stopped
    enabled: false
    masked: true  # Provides the strongest protection against a service being started inadvertently.
