---
- name: Configure system timezone (set {{ timezone }})
  timezone:
    name: "{{ timezone }}"

- name: Install essential system packages
  package:
    name: "{{ common_packages }}"
    state: present

- name: Uninstall useless packages
  package:
    name: "{{ useless_packages }}"
    state: absent
