---
- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/{{ ansible_lsb.id | lower }}/gpg
    state: present 

- name: Add Docker Repository
  apt_repository:
    filename: docker
    repo: deb [arch={{ apt_repo_arch }}] https://download.docker.com/linux/{{ ansible_lsb.id | lower }} {{ ansible_lsb.codename }} stable
    state: present

- name: Update apt and install docker-ce
  apt:
    name: docker-ce
    state: latest
    update_cache: true

- name: Create a /data directory
  file:
    path: /data
    state: directory
    owner: root
    group: "{{ autouser.name }}"
    mode: "0775"
